#!/usr/bin/env bash
# Phase 7: Generate secrets and create .env
# Interactively generates or prompts for all required secrets.

set -euo pipefail

source "$(dirname "${BASH_SOURCE[0]}")/lib/ui.sh"

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENV_FILE="$PROJECT_ROOT/.env"
SECRETS_DIR="$PROJECT_ROOT/secrets"

ui_section "Secrets Configuration"

# Create secrets directory
mkdir -p "$SECRETS_DIR"

# ── Helper Functions ────────────────────────────────────────────────────────

generate_secret() {
  # Generate a random secret of specified length
  local length="${1:-32}"
  openssl rand -base64 "$length" 2>/dev/null | tr -d '\n' | tr -d '=+/' | head -c "$length"
}

generate_key() {
  # Generate a key with a prefix (e.g., sk-)
  local prefix="$1"
  local length="${2:-32}"
  echo "${prefix}$(generate_secret "$length")"
}

secret_exists() {
  local file="$1"
  [[ -f "$file" ]] && [[ -s "$file" ]]
}

get_or_generate() {
  # Get existing secret, or generate/prompt for new one
  local name="$1"
  local file="$2"
  local prompt="$3"
  local prefix="${4:-}"

  if secret_exists "$file"; then
    ui_success "$name: already configured"
    cat "$file"
    return 0
  fi

  if ui_confirm "Generate $prompt automatically?"; then
    local value
    value=$(generate_key "$prefix" 32)
    echo "$value" > "$file"
    chmod 600 "$file"
    ui_success "$name: generated"
    echo "$value"
    return 0
  fi

  local manual
  manual=$(ui_prompt_secret "Enter $prompt")
  if [[ -z "$manual" ]]; then
    ui_error "$name: value cannot be empty"
    return 1
  fi
  echo "$manual" > "$file"
  chmod 600 "$file"
  ui_success "$name: saved"
  echo "$manual"
  return 0
}

# ── PostgreSQL ──────────────────────────────────────────────────────────────

ui_section "PostgreSQL"

postgres_password=$(get_or_generate \
  "PostgreSQL password" \
  "$SECRETS_DIR/postgres_password" \
  "a secure PostgreSQL password")

# ── ClickHouse ─────────────────────────────────────────────────────────────

ui_section "ClickHouse"

clickhouse_password=$(get_or_generate \
  "ClickHouse password" \
  "$SECRETS_DIR/clickhouse_password" \
  "a secure ClickHouse password")

# ── LiteLLM ────────────────────────────────────────────────────────────────

ui_section "LiteLLM"

litellm_master_key=$(get_or_generate \
  "LiteLLM master key" \
  "$SECRETS_DIR/litellm_master_key" \
  "a LiteLLM master key" \
  "sk-litellm-")

# ── Langfuse ───────────────────────────────────────────────────────────────

ui_section "Langfuse"

langfuse_secret_key=$(get_or_generate \
  "Langfuse secret key" \
  "$SECRETS_DIR/langfuse_secret_key" \
  "a Langfuse secret key" \
  "sk-langfuse-")

langfuse_salt=$(get_or_generate \
  "Langfuse salt" \
  "$SECRETS_DIR/langfuse_salt" \
  "a Langfuse salt")

nextauth_secret=$(get_or_generate \
  "NextAuth secret" \
  "$SECRETS_DIR/nextauth_secret" \
  "a NextAuth secret")

# ── Write .env ─────────────────────────────────────────────────────────────

ui_section "Writing .env"

cat > "$ENV_FILE" <<EOF
# GENERATED BY bootstrap.sh — DO NOT EDIT
# Edit files in secrets/ and re-run ./bootstrap.sh render

# PostgreSQL
POSTGRES_USER=postgres
POSTGRES_PASSWORD=${postgres_password}
POSTGRES_DB=platform_db

# LiteLLM
LITELLM_MASTER_KEY=${litellm_master_key}
LITELLM_DATABASE_URL=postgresql://postgres:${postgres_password}@postgres:5432/platform_db

# Langfuse
LANGFUSE_SECRET_KEY=${langfuse_secret_key}
LANGFUSE_SALT=${langfuse_salt}
NEXTAUTH_SECRET=${nextauth_secret}
NEXTAUTH_URL=http://localhost:3000

# ClickHouse
CLICKHOUSE_USER=clickhouse
CLICKHOUSE_PASSWORD=${clickhouse_password}

# Platform & Inference Settings
INFERENCE_HOST=127.0.0.1
INFERENCE_PORT=8080
PLATFORM_DOMAIN=ai.xynotech.internal
EOF

chmod 600 "$ENV_FILE"
ui_success ".env written with all secrets"