from pathlib import Path
from platform.config import ResolvedPlatform, ServiceManifest
from typing import Any

import yaml
from jinja2 import Environment, FileSystemLoader


class IndentedDumper(yaml.Dumper):
    def increase_indent(self, flow: bool = False, indentless: bool = False) -> Any:
        return super().increase_indent(flow=flow, indentless=False)


def _render_service_templates(root_dir: Path, resolved: ResolvedPlatform) -> list[Path]:
    """Render all Jinja2 templates in templates/<service>/ to configs/<service>/."""
    templates_dir = root_dir / "templates"
    configs_dir = root_dir / "configs"
    rendered_files: list[Path] = []

    if not templates_dir.exists():
        return rendered_files

    context = {
        "platform": resolved.config.model_dump(),
        "versions": resolved.versions.model_dump(),
        "services": {k: v.model_dump() for k, v in resolved.services.items()},
    }

    env = Environment(loader=FileSystemLoader(str(templates_dir)), autoescape=False)

    for service_name in resolved.config.services:
        service_template_dir = templates_dir / service_name
        if not service_template_dir.exists():
            continue

        output_dir = configs_dir / service_name
        output_dir.mkdir(parents=True, exist_ok=True)

        for template_path in service_template_dir.glob("*.j2"):
            output_filename = template_path.stem
            output_file = output_dir / output_filename

            template = env.get_template(f"{service_name}/{template_path.name}")
            rendered_content = template.render(**context)

            if not rendered_content.endswith("\n"):
                rendered_content += "\n"

            output_file.write_text(rendered_content)
            rendered_files.append(output_file)

    return rendered_files


def generate_compose_dict(resolved: ResolvedPlatform) -> dict[str, Any]:
    """Generate compose dictionary structure from resolved platform."""
    compose_services: dict[str, Any] = {}

    for service_name in resolved.dependency_order:
        manifest: ServiceManifest = resolved.services[service_name]
        version_tag = resolved.versions.services.get(manifest.version_key, "latest")
        image_name = f"{manifest.image}:{version_tag}"

        svc_dict: dict[str, Any] = {
            "image": image_name,
            "container_name": service_name,
            "restart": "unless-stopped",
            "networks": [resolved.config.network.name],
        }

        # Ports
        if manifest.ports:
            svc_dict["ports"] = [f"{p.host_port}:{p.container_port}" for p in manifest.ports]

        # Volumes
        if manifest.volumes:
            svc_dict["volumes"] = [f"{v.source}:{v.target}" for v in manifest.volumes]

        # Environment
        if manifest.environment:
            svc_dict["environment"] = {
                env_var: f"${{{env_var}}}" for env_var in manifest.environment
            }

        # Environment File
        if manifest.env_file:
            svc_dict["env_file"] = manifest.env_file

        # Depends On
        if manifest.depends_on:
            svc_dict["depends_on"] = {
                dep: (
                    {"condition": "service_healthy"}
                    if resolved.services[dep].health
                    else {"condition": "service_started"}
                )
                for dep in manifest.depends_on
                if dep in resolved.config.services
            }

        # Health Check
        if manifest.health:
            hc: dict[str, Any] = {
                "interval": manifest.health.interval,
                "timeout": manifest.health.timeout,
                "retries": manifest.health.retries,
            }
            if manifest.health.command:
                cmd = list(manifest.health.command)
                if cmd and cmd[0] not in ("CMD", "CMD-SHELL", "NONE"):
                    cmd.insert(0, "CMD")
                hc["test"] = cmd
            elif manifest.health.endpoint:
                c_port = manifest.ports[0].container_port
                test_cmd = f"curl -f http://localhost:{c_port}{manifest.health.endpoint} || exit 1"
                hc["test"] = ["CMD-SHELL", test_cmd]
            svc_dict["healthcheck"] = hc

        compose_services[service_name] = svc_dict

    compose_dict = {
        "name": resolved.config.name,
        "services": compose_services,
        "networks": {resolved.config.network.name: {"driver": "bridge"}},
    }

    return compose_dict


def _render_compose_yaml(root_dir: Path, resolved: ResolvedPlatform) -> Path:
    """Generate compose.yaml file at root directory."""
    compose_dict = generate_compose_dict(resolved)
    compose_path = root_dir / "compose.yaml"
    header = "# GENERATED FILE - DO NOT EDIT MANUALLY\n# Generated by platform.renderer\n\n"
    yaml_content = yaml.dump(compose_dict, Dumper=IndentedDumper, sort_keys=False)
    if not yaml_content.endswith("\n"):
        yaml_content += "\n"
    compose_path.write_text(header + yaml_content)
    return compose_path


def render_all(root_dir: Path, resolved: ResolvedPlatform) -> list[Path]:
    """Render all config templates and compose.yaml."""
    templates_dir = root_dir / "templates"
    for service_name in resolved.config.services:
        manifest = resolved.services.get(service_name)
        if manifest and manifest.volumes:
            for v in manifest.volumes:
                source_path = (
                    root_dir / v.source if not Path(v.source).is_absolute() else Path(v.source)
                )
                if source_path.exists():
                    if source_path.is_file():
                        source_path.parent.mkdir(parents=True, exist_ok=True)
                    else:
                        source_path.mkdir(parents=True, exist_ok=True)
                else:
                    template_file = templates_dir / service_name / f"{source_path.name}.j2"
                    if template_file.exists():
                        source_path.parent.mkdir(parents=True, exist_ok=True)
                    else:
                        source_path.mkdir(parents=True, exist_ok=True)

    rendered = _render_service_templates(root_dir, resolved)
    compose_path = _render_compose_yaml(root_dir, resolved)
    rendered.append(compose_path)
    return rendered
